### ISSUE TITLE
Return all possible values for unions?

### ISSUE THREAD

**Issue by rexxars** [EasyGraphQL/easygraphql-mock#28]
Hi,

Phenomenal project <3

I'm wondering whether it would be possible to pass an option in order for the mocking to generate all possible values for unions, instead of a random one.

For instance, consider:
```
union AuthorWork = Project | BlogPost

type Author {
  name: string
  favoriteWork: AuthorWork
  work: [AuthorWork]
}
```

In this case, it would be really awesome if instead of just returning either a blog post or a work, it could return both. In the case of arrays, this could be done by simply adding both to the array, whereas representing both for a regular field will require a change so that the `Author` key on the object returned would be an array instead of an object.

Thoughts?

**Comment by estrada9166** [comment]
@rexxars Thanks for writing! 

Ok, so, the main idea is that when it's `[AuthorWork]`, it'll return an array with `Project` and `BlogPost` instead of a project or blogpost (random one), right? 

Also, can you explain me a little bit more:
> whereas representing both for a regular field will require a change so that the Author key on the object returned would be an array instead of an object.

Thanks!!

**Comment by rexxars** [comment]
Sorry about the vague description.

The `work` field, since it is an array, is fairly easy to mock values for:

```js
{
  "name": "Alejandro",
  "work": [
    {
      "__typename": "Project",
      "some": "... project props"
    },
    {
      "__typename": "BlogPost",
      "other": "... blog post props"
    }
  ]
}
```

However, the `favoriteWork` field is not in a list, so it has to return _either_ a project or a blog post. By returning arrays of nodes instead of a single node, this could be fixed:

```js
const result = easyGraphQLMock(someSchema)
// Result:
{
  "Author": [
    {
      "name": "Alejandro",
      "favoriteWork": {
        "__typename": "Project",
        "some": "... project props"
      },
      "work": [
        {
          "__typename": "Project",
          "some": "... project props"
        },
        {
          "__typename": "BlogPost",
          "other": "... blog post props"
        }
      ],
    },
    {
      "name": "Espen",
      "favoriteWork": {
        "__typename": "BlogPost",
        "other": "... blog post props"
      },
      "work": [
        {
          "__typename": "Project",
          "some": "... project props"
        },
        {
          "__typename": "BlogPost",
          "other": "... blog post props"
        }
      ],
    }
  ]
}
```

**Comment by estrada9166** [comment]
Thanks for explaining it better!!

To set the `work` with all the types, definitely it should have it, so, if you want to work on a PR, it'll be great, I can help you!!

Also, I'm not sure about making a type an array of nodes instead of a single node... there is something that you can do to solve your need and it can be something like this:

```js
const mock = easyGraphQLMock(someSchema)

let authorWithBlogPost = Object.assign({}, mock.Author)
authorWithBlogPost.favoriteWork = mock.BlogPost

let authorWithProject = Object.assign({}, mock.Author)
authorWithProject.favoriteWork = mock.Project
``` 
As you can see, the `mock` will have all the types that you set on your schema! 

What do you think?

**Comment by rexxars** [comment]
Hmm, that _is_ a solution, but it requires knowledge about the schema upfront. I'm using this as part of an automated tool where I don't have any knowledge of the schema. I would have to introspect the schema and figure out which fields are union fields, then resolve the possible types for those union fields, then grab the values from the mock. In no way impossible, but certainly less magic than the current solution ;)
