### ISSUE TITLE
State kept between runs

### ISSUE THREAD

**Issue by rexxars** [EasyGraphQL/easygraphql-mock#31]
```js
const easygraphqlMock = require('easygraphql-mock')

const schema1 = `
type Author {
  name: String
}
`

const schema2 = `
type Author {
  title: String
  favoriteProject: Project
}

type Project {
  name: String
}
`

console.log('Schema 1')
console.log(easygraphqlMock(schema1))

console.log('')

console.log('Schema 2')
console.log(easygraphqlMock(schema2))
```

Running this yields:

```
Schema 1
{ Author: { __typename: 'Author', name: 'Annie' } }

Schema 2
{ Author: { __typename: 'Author', name: 'Annie' },
  Project: { __typename: 'Project', name: 'Jeremiah' } }
```

As you can see, the `Author` type uses the type from the first run in the second call, where `name` isn't a property, and `favoriteProject` is not set.

**Comment by estrada9166** [comment]
@rexxars Thank you so much! I'll push soon the fix, the cache was not removed after the mock ends, so, that's why you were having the first schema twice!!

Thank you so much for creating these issues, so we can continue improving easygraphql-mock :)

**Comment by estrada9166** [comment]
@rexxars There is a new version `0.1.9` with the fix!!

Let me know if it works, so we can close this issue!

**Comment by rexxars** [comment]
Yup, that fixed it! Thanks a bunch, Alejandro!
